apiVersion: v1
appVersion: 2.0.0.5344-ls60
description: Sonarr is a television show downloading client
name: sonarr
version: 4.1.3
keywords:
  - sonarr
  - usenet
  - bittorrent
home: https://github.com/billimek/billimek-charts/tree/master/charts/sonarr
icon: https://avatars1.githubusercontent.com/u/1082903?s=400&v=4
sources:
  - https://hub.docker.com/r/linuxserver/sonarr/
  - https://sonarr.tv/
maintainers:
  - name: billimek
    email: jeff@billimek.com
