apiVersion: v1
appVersion: 2.3.9
description: Free and easy binary newsreader
name: sabnzbd
version: 1.0.2
keywords:
  - sabnzbd
  - usenet
home: https://github.com/billimek/billimek-charts/tree/master/charts/sabnzbd
icon: https://avatars1.githubusercontent.com/u/960698?s=400&v=4
sources:
  - https://hub.docker.com/r/linuxserver/sabnzbd/
  - https://sabnzbd.org/
maintainers:
  - name: billimek
    email: jeff@billimek.com
