{{- if and .Values.openvpn.enabled ( or .Values.openvpn.env .Values.openvpn.auth )}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nzbget.fullname" . }}-openvpnenv
  labels:
    app.kubernetes.io/name: {{ include "nzbget.name" . }}
    helm.sh/chart: {{ include "nzbget.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- if .Values.openvpn.auth }}
  VPN_AUTH: {{ .Values.openvpn.auth | b64enc }}
  {{- end }}
  {{- if .Values.openvpn.env }}
  {{- range $k, $v := .Values.openvpn.env }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
  {{- end -}}
{{- end -}}