{{- if .Values.openvpn.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "nzbget.fullname" . }}-deny-all-netpol
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nzbget.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Egress
  egress:
  {{- if .Values.openvpn.networkPolicy.egress }} 
  {{- .Values.openvpn.networkPolicy.egress | toYaml | nindent 4 }}
  {{- end -}}
{{- end -}}