apiVersion: v1
appVersion: v0.8.4.2-ls72
description: Bazarr is a companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements
name: bazarr
version: 2.0.2
keywords:
  - bazarr
  - radarr
  - sonarr
  - subtitles
  - usenet
  - bittorrent
home: https://github.com/billimek/billimek-charts/tree/master/charts/bazarr
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bazarr.png
sources:
  - https://hub.docker.com/r/linuxserver/bazarr/
  - https://github.com/morpheus65535/bazarr
maintainers:
  - name: billimek
    email: jeff@billimek.com
