apiVersion: v1
appVersion: 1.0.6-12
description: Node-RED is low-code programming for event-driven applications
name: node-red
version: 2.0.2
keywords:
  - nodered
  - node-red
home: https://github.com/billimek/billimek-charts/tree/master/charts/node-red
icon: https://nodered.org/about/resources/media/node-red-icon-2.png
sources:
  - https://github.com/node-red/node-red-docker
  - https://github.com/billimek/billimek-charts/tree/master/charts/node-red
maintainers:
  - name: billimek
    email: jeff@billimek.com
  - name: batazor
    email: batazor111@gmail.com
