apiVersion: v1
appVersion: "v0.8"
description: DNS proxy as ad-blocker for local network
name: blocky
version: 3.3.0
keywords:
  - blocky
  - dbs
home: https://github.com/billimek/billimek-charts/tree/master/charts/blocky
icon: https://github.com/0xERR0R/blocky/raw/master/docs/blocky.svg?sanitize=true
sources:
  - https://github.com/0xERR0R/blocky
maintainers:
  - name: billimek
    email: jeff@billimek.com
