apiVersion: v1
kind: Service
metadata:
  name: {{ include "deconz.fullname" . }}
  labels:
    {{- include "deconz.labels" . | nindent 4 }}
spec:
  {{- if (or (eq .Values.service.type "ClusterIP") (empty .Values.service.type)) }}
  type: ClusterIP
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{end}}
  {{- else if eq .Values.service.type "LoadBalancer" }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
  {{- else }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
  {{ toYaml .Values.service.externalIPs | indent 4 }}
  {{- end }}
  publishNotReadyAddresses: {{ .Values.service.publishNotReadyAddresses }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{.Values.service.nodePort}}
      {{ end }}
    - port: {{ .Values.service.websocketPort }}
      targetPort: websocket
      protocol: TCP
      name: websocket
    {{- if .Values.vnc.enabled }}
    - port: {{ .Values.service.vncPort }}
      targetPort: vnc
      protocol: TCP
      name: vnc
    {{- end }}
  selector:
    {{- include "deconz.selectorLabels" . | nindent 4 }}
