apiVersion: v2
name: deconz
description: A Helm chart for deploying deCONZ
version: 1.0.1
appVersion: 2.05.79
keywords:
  - deconz
  - home-automation
  - zigbee
home: https://github.com/billimek/billimek-charts/tree/master/charts/deconz
icon: https://avatars1.githubusercontent.com/u/4217524?s=400&v=4
sources:
  - https://github.com/dresden-elektronik/deconz-rest-plugin
  - https://github.com/marthoc/docker-deconz
maintainers:
  - name: billimek
    email: jeff@billimek.com
